import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossOrigin="anonymous"></link>
      </Head>

    <div className="form-wrap">
      <div className="center">
        <form action="/api/form" method="post">
          <div className="mb-3">
            <label htmlFor="visma-url-input" className="form-label">Visma Url</label>
            <input className="form-control" id="visma-url-input" aria-describedby="visma-url-help" />
            <div id="visma-url-help" className="form-text">Enter the visma website to scrape</div>
          </div>
          <div className="mb-3">
            <label htmlFor="result-file-name" className="form-label">Result File Name</label>
            <input className="form-control" id="result-file-name" aria-describedby="result-file-help"/>
            <div id="result-file-help" className="form-text">Enter the result file name</div>
          </div>
          <button type="submit" className="btn btn-primary">Submit</button>
        </form>
      </div>

    </div>

    </>
  )
}
