import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <form action="/api/form" method="post">
            <label htmlFor="website">Website:</label>
            <input type="text" id="website" name="website" />
            <button type="submit">Submit</button>
          </form>
    </>
  )
}
